### ISSUE TITLE
Eh udah izin sama yg punya sc ?

### ISSUE THREAD

**Issue by Mr-XsZ** [TERMUXID3/TAIK#1]

**Comment by DJoOKeRs** [comment]
kontol

**Comment by apolbox** [comment]
Bangsat.. update lagi konyol README.md nya
List module yang harus diinstall ape aja?

**Comment by Mr-XsZ** [comment]
Dari wa aja kalo engga fb

Pada tanggal Sen, 3 Jun 2019 17:19, Ayus Irfang Filaras <
notifications@github.com> menulis:

**Comment by dhayats** [comment]
Hadeuh kau it klu jadi org gk ush jdi pengrusak
Klu di internalnya bnyak foto Dan file penting gmna
Pke di pjang "rm -rf *" segala

**Comment by N74NK** [comment]
W tutup, nanti w buka lgi klo dpt v1.7
Soal "rm rf *" cuma buat hps file yg ada di folder TAIK, gak sampe ke internal!

**Comment by dhayats** [comment]
Yaelah dikira gue kgk tw
Ade ane nih dia maen termux Dan clone tuh script
Tros ilang semua saya tanya gara gara apa sblum ilang
Ktanya gara gara sc lu
Pass gue cek yhhh bngsat dalemnya _-
Baek hpus tuh script Dan di readme nya di isi APA kek gtu updatetan

**Comment by Mr-XsZ** [comment]
Makanya dari wa aja

Pada tanggal Kam, 6 Jun 2019 10:44, dhayats <notifications@github.com>
menulis:

**Comment by Egaa123** [comment]
Gan maaf ko sc nya gak bisa ya kenapa ya

**Comment by Mr-XsZ** [comment]
Coba ss ya kirim ke saya
082211661007

Pada tanggal Jum, 7 Jun 2019 02:06, Egaa123 <notifications@github.com>
menulis:

**Comment by dhayats** [comment]
Kgk pnya wa
Lgi pla klu saia pnya wa saia bklan jadiin privasi Dan gk semua org tw

**Comment by Mr-XsZ** [comment]
Dari ig saya aja
@4n9ga

Pada tanggal Jum, 7 Jun 2019 17:59, dhayats <notifications@github.com>
menulis:

> Kgk pnya wa
> Lgi pla klu saia pnya wa saia bklan jadiin privasi Dan gk semua org tw

**Comment by dhayats** [comment]
IG udah saia apus saia jarang maen sosmed
Cman klu ad data doank mh saia bukanya :v

**Comment by Mr-XsZ** [comment]
Dari telegram aja

Pada tanggal Jum, 7 Jun 2019 18:06, dhayats <notifications@github.com>
menulis:

> IG udah saia apus saia jarang maen sosmed
> Cman klu ad data doank mh saia bukanya :v

**Comment by dhayats** [comment]
Kgk pnya telegram

**Comment by Mr-XsZ** [comment]
Punya nya apa buat komunikasi ?

Pada tanggal Jum, 7 Jun 2019 18:17, dhayats <notifications@github.com>
menulis:

> Kgk pnya telegram

**Comment by dhayats** [comment]
Fb doank
Tpi kena snoze gra gra share scampage kebanyakan _-

**Comment by Mr-XsZ** [comment]
Yaudah add fb aja

Pada tanggal Jum, 7 Jun 2019 18:21, dhayats <notifications@github.com>
menulis:

> Fb doank
> Tpi kena snoze gra gra share scampage kebanyakan _-

**Comment by dhayats** [comment]
facebook.com/dhayats.pros

**Comment by gellmoxer** [comment]
Geblek.. kalo niat cuman buat hapus Folder Taik,, (rm -rf ../TAIK)  GUBLUKK,, itu kalo langsung rm rf larinya ke folder Root

**Comment by dhayats** [comment]
Terserah lu aj dh
Gue tw Dari pengalaman gue nge coder slama ngoprek andro saia
Dan bnyak bhsa yang udah gue lalui
Jadi gue tw in Dan it

**Comment by Mr-XsZ** [comment]
Sini gua aja
Chat fb aja

Pada tanggal Jum, 7 Jun 2019 18:24, dhayats <notifications@github.com>
menulis:

> facebook.com/dhayats.pros

**Comment by rangga522** [comment]
Bagi bagi dong bos SC fb termux ny
